import type { Metadata } from "next";
import {
  Audiowide,
  Cal_Sans,
  Geist,
  Geist_Mono,
  Golos_Text,
} from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/navbar";
import Footer from "./Components/Footer/Footer";

const audiowide = Audiowide({
  weight: "400",
  variable: "--font-audiowide",
  subsets: ["latin"],
});

const golostext = Golos_Text({
  weight: "400",
  variable: "--font-golostext",
  subsets: ["latin"],
});
const calsans = Cal_Sans({
  weight: "400",
  variable: "--font-calsans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${golostext.variable} ${audiowide.variable} ${calsans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
